### ISSUE TITLE
Delete unused entry points

### ISSUE THREAD

**Issue by jbonot** [jbonot/py-pdf-reader#2]
### To-Do
- [ ] Delete deprecated GUI: `app.py`, `app.spec`
- [ ] Delete console script: `main.py`, `main.spec`
- [ ] Rename `app_themed` to `main`
- [ ] Update `justfile`
